### ISSUE TITLE
CSS enhancement for splitting elements into individual visual fragments

### ISSUE THREAD

**Issue by kizu** [kizu/ideas#107]
``` css
.test {
  fragments: polygon() polygon() …
}
```

then

``` css
.test:fragment(1) {
  transform: …;
}
```

etc.
